# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno and run tests across stable and nightly builds on Windows, Ubuntu and macOS.
# For more information see: https://github.com/denolib/setup-deno

name: Deno

on:
  push:
    branches: [jentest]
  pull_request:
    branches: [jentest]

jobs:
  test:
    runs-on: ${{ matrix.os }} # runs a test on Ubuntu, Windows and macOS

    strategy:
      matrix:
#         deno: ["v1.x", "nightly"]
        deno: ["v1.x"]
        os: [ubuntu-latest]

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

#       - name: Setup Deno
#         uses: denolib/setup-deno@c7d7968ad4a59c159a777f79adddad6872ee8d96
#         with:
#           deno-version: ${{ matrix.deno }} # tests across multiple Deno versions

#       - name: Cache Dependencies
#         run: deno cache deps.ts

#       - name: Run Tests
#         run: deno test -A --unstable

      - name: ls before
        shell: sh
        run: ls
        
#       - name: npm install
#         shell: sh
#         run: npm install
      
#       - name: npm lint
#         shell: sh
#         run: npm run-script lint

#       - name: npm build
#         shell: sh
#         run: npm run-script build --prod --aot
        
      - name: ls after
        shell: sh
        run: ls
      
#       - name: FTP Deploy
#       # You may pin to the exact commit or the version.
#       # uses: SamKirkland/FTP-Deploy-Action@bc95d3edc3de87143284e6707ac140ce6dcbe29c
#         uses: SamKirkland/FTP-Deploy-Action@4.0.0
#         with:
#           # ftp server
#           server: 91.219.122.5
#           # ftp username
#           username: ${{secrets.WEBIO_USER}}
#           # ftp password
#           password: ${{secrets.WEBIO_PASS}}
#           # Server port to connect to (read your web hosts docs)
# #           port: # optional
#           # protocol to deploy with - ftp, ftps, or ftps-legacy
# #           protocol: # optional
#           # Folder to upload from, must end with trailing slash /
#           local-dir: src/  # optional
#           # Path to upload to on the server. Must end with trailing slash /
#           server-dir: eoroid2144.hostingasp.pl/wwwroot/ftpgit/ # optional
#           # Path and name of the state file - this file is used to track which files have been deployed
# #           state-name: upload.log # optional
#           # Prints which modifications will be made with current config options, but doesnt actually make any changes
# #           dry-run: true # optional
#           # Deletes ALL contents of server-dir, even items in excluded with exclude argument
# #           dangerous-clean-slate: # optional
#           # An array of glob patterns, these files will not be included in the publish/delete process
# #           exclude: # optional
#           # How verbose should the information be - warn, info, debug
#           log-level: verbose # optional
#           # strict or loose
# #           security: # optional

      - name: git-ftp-action
        # You may pin to the exact commit or the version.
        # uses: sebastianpopp/git-ftp-action@33a94c0e0fce59ca477baa9d1748a5f2e53fb429
        uses: sebastianpopp/git-ftp-action@3.0.0
        with:
          # URL
          url: ftp://91.219.122.5/eoroid2144.hostingasp.pl/wwwroot/ftpgit3/
          # FTP login name
          user: ${{secrets.WEBIO_USER}}
          # FTP password
          password: ${{secrets.WEBIO_PASS}}
          # Specifies a local directory to sync from as if it were the git project root path.
          syncroot: src/ # optional, default is .
          # Additional options
#           options: # optional, default is --auto-init



